apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: my-config
    patch: |-
      - op: replace
        path: /data/greeting
        value: "Quick fix greeting"
