apiVersion: v1
kind: Service
metadata:
  name: blue-app-jason
  labels:
    app: blue-app-jason
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30084
  selector:
    app: blue-app-jason
