apiVersion: v1
kind: Service
metadata:
  name: yellow-app
  labels:
    app: yellow-app
spec:
  type: NodePort
  selector:
    app: yellow-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30085
