apiVersion: v1
kind: Service
metadata:
  name: sync-form-app-temp
  labels:
    app: sync-form-app
spec:
  type: ClusterIP
  selector:
    app: sync-form-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
