version: '3.8'

services:
  argocd-server:
    image: quay.io/argoproj/argocd:v2.8.4
    container_name: argocd-server
    command: [argocd-server, --insecure, --namespace, argocd]
    ports:
      - "8088:8080"
    environment:
      - ARGOCD_SERVER_INSECURE=true
      - KUBECONFIG=/home/argocd/.kube/config
      - ARGOCD_SERVER_NAMESPACE=argocd
    volumes:
      - argocd-data:/home/argocd
      - ~/.kube:/home/argocd/.kube:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: argocd-redis
    restart: unless-stopped

  argocd-repo-server:
    image: quay.io/argoproj/argocd:v2.8.4
    container_name: argocd-repo-server
    command: [argocd-repo-server, --namespace, argocd]
    environment:
      - KUBECONFIG=/home/argocd/.kube/config
      - ARGOCD_SERVER_NAMESPACE=argocd
    volumes:
      - argocd-data:/home/argocd
      - ~/.kube:/home/argocd/.kube:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - redis

  argocd-application-controller:
    image: quay.io/argoproj/argocd:v2.8.4
    container_name: argocd-application-controller
    command: [argocd-application-controller, --namespace, argocd]
    environment:
      - KUBECONFIG=/home/argocd/.kube/config
      - ARGOCD_SERVER_NAMESPACE=argocd
    volumes:
      - argocd-data:/home/argocd
      - ~/.kube:/home/argocd/.kube:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  argocd-data: